### ISSUE TITLE
支持win10环境？我执行完命令提醒download complete，但是没有数据下载成功

### ISSUE THREAD

**Issue by tuhaolam** [dearplain/douding#2]

**Comment by dearplain** [comment]
你没有提供任何信息用于重现。

**Comment by tuhaolam** [comment]
后面重新build过之后就可以了。上面说的是douding的，baiduwenku的才是运行不成功的。
```
douding_baiduwenku_downloader.exe https://wenku.baidu.com/view/f79b89447fd5360cba1adb75.html
panic: runtime error: index out of range

goroutine 1 [running]:
main.downWenkuPPT(0xc042080080, 0x3a)
        D:/tuhao/golang/douding_baiduwenku_downloader.go:50 +0x9d3
main.main()
        D:/tuhao/golang/douding_baiduwenku_downloader.go:31 +0x13e
```

**Comment by dearplain** [comment]
豆丁下载 百度文库ppt下载
现在还不支持pdf。

**Comment by tuhaolam** [comment]
对golang语法不太懂，下面是python的实现。
```
def PDF(url):
    doc_id = re.findall('view/(.*).html',url)[0]
    url = "https://wenku.baidu.com/browse/getbcsurl?doc_id="+doc_id+"&pn=1&rn=99999&type=ppt"
    html = requests.get(url).text
    lists=re.findall('{"zoom":"(.*?)","page"',html)
    for i in range(0,len(lists)):
        lists[i] = lists[i].replace("\\",'')
    try:
        os.mkdir(doc_id)
    except:
        pass
    for i in range(0,len(lists)):
        img=requests.get(lists[i]).content
        with open(doc_id+'/img'+str(i)+'.jpg','wb') as m:
            m.write(img)
    print("PDF图片保存在" + doc_id + "文件夹")
```

**Comment by dearplain** [comment]
try again.
